[package]
name = "sputnikvm"
version = "0.10.1"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "SputnikVM - a Portable Blockchain Virtual Machine"
repository = "https://github.com/ethereumproject/sputnikvm"
keywords = ["no_std", "ethereum"]

[lib]
name = "sputnikvm"

[dependencies]
sha3 = "0.6"
sha2 = "0.6"
ripemd160 = "0.6"
digest = "0.6"
etcommon-block-core = { version = "0.1", default-features = false }
etcommon-rlp = { version = "0.2", default-features = false }
etcommon-bigint = { version = "0.2", default-features = false, features = ["rlp"] }

etcommon-block = { version = "0.3", default-features = false, optional = true }
secp256k1-plus = { version = "0.5.7", optional = true }
libsecp256k1 = { version = "0.1", optional = true }
log = "0.4.3"

[dev-dependencies]
etcommon-hexutil = "0.2"

[features]
default = ["std", "c-secp256k1"]
c-secp256k1 = ["secp256k1-plus", "etcommon-block/c-secp256k1"]
rust-secp256k1 = ["libsecp256k1", "etcommon-block/rust-secp256k1"]
std = ["etcommon-block-core/std", "etcommon-rlp/std", "etcommon-bigint/std", "etcommon-block"]

[workspace]
members = [
  "./jsontests",
  "./regtests",
  "./gethrpc",
  "./stateful",
  "./cli",
  "./precompiled/modexp",
  "./precompiled/bn128",
  "./network/foundation",
  "./network/classic",
  "./network/ellaism",
  "./network/musicoin",
  "./network/expanse",
  "./network/ubiq",
]
